### ISSUE TITLE
Empty repo

### ISSUE THREAD

**Issue by michaeljklein** [GaloisInc/hexdump#1]
Hey, I just wanted to update the repo for stack, but it's empty. Put anything in it and I'll send a PR from: https://github.com/michaeljklein/hexdump-temp/tree/master

**Comment by glguy** [comment]
We should definitely have the code actually in this repository, but stack.yaml files don't belong in library repositories. They are local workspace configuration. hexdump.cabal will contain all the information needed. Someone working on the package could use stack init to start a new workspace if they were doing development on the package.

**Comment by glguy** [comment]
Repo populated! That only took a few years to happen, yikes!
